-- Sửa lỗi ORA-00942 bằng cách tạo lại bảng QR_Login trong đúng schema

-- Bước 1: Xóa bảng QR_Login cũ nếu nó tồn tại trong schema hiện tại
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE QR_Login';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- Bước 2: Tạo lại bảng QR_Login trong schema TADMIN
CREATE TABLE TADMIN.QR_Login (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SessionKey NVARCHAR2(100) UNIQUE,
    UserId NUMBER,
    IsUsed NUMBER(1) DEFAULT 0,
    CreatedAt DATE DEFAULT SYSDATE,
    CONSTRAINT fk_qr_login_user FOREIGN KEY (UserId) REFERENCES TADMIN.KhachHang(MaKhachHang)
);
/

-- Bước 3 (Tùy chọn): Nếu ứng dụng của bạn kết nối bằng một user khác không phải TADMIN,
-- bạn cần cấp quyền cho user đó. Thay thế 'APP_USER' bằng user của bạn.
-- GRANT SELECT, INSERT, UPDATE, DELETE ON TADMIN.QR_Login TO APP_USER;
-- /
