create table khachhang (
   makhachhang     number generated by default as identity primary key,
   hoten           nvarchar2(100),
   email           nvarchar2(100) unique not null,
   sodienthoai     nvarchar2(20),
   diachi          nvarchar2(200),
   vaitro          nvarchar2(20) default 'KhachHang' check ( vaitro in ( 'Admin',
                                                                'KhachHang',
                                                                'NhanVien' ) ),
   trangthai       nvarchar2(20) default 'HoatDong' check ( trangthai in ( 'HoatDong',
                                                                     'BiKhoa' ) ),
   ngaytao         date default sysdate,
   oracle_username nvarchar2(100)
);

create table nhanvien (
   manhanvien      number generated by default as identity primary key,
   hoten           nvarchar2(100),
   email           nvarchar2(100) unique not null,
   sodienthoai     nvarchar2(20),
   vaitro          nvarchar2(20) default 'NhanVien' check ( vaitro in ( 'Admin',
                                                               'NhanVien' ) ),
   trangthai       nvarchar2(20) default 'HoatDong' check ( trangthai in ( 'HoatDong',
                                                                     'BiKhoa' ) ),
   ngaytao         date default sysdate,
   machinhanh      number,
   oracle_username nvarchar2(100),
   constraint fk_nv_cn foreign key ( machinhanh )
      references chinhanh ( machinhanh )
);

create table tour (
   matour      number generated by default as identity primary key,
   tieude      nvarchar2(200),
   mota        nvarchar2(500),
   noikhoihanh nvarchar2(100),
   noiden      nvarchar2(100),
   thanhpho    nvarchar2(100),
   thoigian    date,
   gianguoilon number(12,2),
   giatreem    number(12,2),
   trangthai   nvarchar2(50) default 'Hoạt động' check ( trangthai in ( 'Hoạt động',
                                                                      'Đang diễn ra',
                                                                      'Hoàn thành',
                                                                      'Tạm ngưng',
                                                                      'Đã kết thúc',
                                                                      'Đã hủy',
                                                                      'Ẩn' ) ),
   soluong     number,
   qr          clob,
   machinhanh  number,
   chinhanh    nvarchar2(100),
   constraint fk_tour_cn foreign key ( machinhanh )
      references chinhanh ( machinhanh )
);


create table anhtour (
   maanh      number generated by default as identity primary key,
   matour     number,
   dulieuanh  blob,
   loaianh    nvarchar2(50),
   mota       nvarchar2(200),
   ngaytailen date default sysdate,
   constraint fk_anh_tour foreign key ( matour )
      references tour ( matour )
);

create table dattour (
   madattour          number generated by default as identity primary key,
   makhachhang        number,
   matour             number,
   ngaydat            date default sysdate,
   songuoilon         number,
   sotreem            number,
   tongtien           number(12,2),
   trangthaithanhtoan nvarchar2(30) default N'Chưa thanh toán' check ( lower(trangthaithanhtoan) in ( 'chưa thanh toán',
                                                                                                      'đã thanh toán' ) ),
   trangthaidat       nvarchar2(30) default N'Chờ xác nhận' check ( lower(trangthaidat) in ( 'chờ xác nhận',
                                                                                       'chưa xác nhận',
                                                                                       'đã xác nhận',
                                                                                       'đã hủy',
                                                                                       'đã hoàn thành',
                                                                                       'hoàn thành',
                                                                                       'đã thanh toán' ) ),
   yeucaudacbiet      nvarchar2(200),
   constraint fk_dattour_kh foreign key ( makhachhang )
      references khachhang ( makhachhang ),
   constraint fk_dattour_tour foreign key ( matour )
      references tour ( matour )
);

create table hoadon (
   mahoadon  number generated by default as identity primary key,
   madattour number,
   sotien    number(12,2),
   ngayxuat  date default sysdate,
   trangthai nvarchar2(30) default N'Chưa thanh toán' check ( lower(trangthai) in ( 'chưa thanh toán',
                                                                                    'đã thanh toán',
                                                                                    'hoàn tất' ) ),
   chukyso   nvarchar2(500),
   payload   clob,
   constraint fk_hd_dt foreign key ( madattour )
      references dattour ( madattour )
);

create table qr_login (
   id         number generated by default as identity primary key,
   sessionkey nvarchar2(100) unique,
   userid     number,
   isused     number(1) default 0,
   createdat  date default sysdate,
   constraint fk_qr_user foreign key ( userid )
      references khachhang ( makhachhang )
);
create table chinhanh (
   machinhanh  number generated by default as identity primary key,
   tenchinhanh nvarchar2(100) not null,
   diachi      nvarchar2(200),
   sodienthoai nvarchar2(20)
);

create table tadmin.user_sessions (
   session_id    varchar2(64) primary key,
   user_id       number not null,
   user_type     nvarchar2(20) not null,
   device_type   nvarchar2(10) default 'WEB' not null,
   login_time    timestamp default systimestamp,
   last_activity timestamp default systimestamp,
   ip_address    nvarchar2(50),
   device_info   nvarchar2(200),
   is_active     char(1) default 'Y' not null
);

create index idx_user_session_status on
   tadmin.user_sessions (
      user_id,
      user_type,
      is_active
   );

-- =====================================================
-- 4. PROFILE KIỂM SOÁT ĐĂNG NHẬP
-- =====================================================
create profile admin_profile limit
   failed_login_attempts 3             -- Sai mật khẩu 3 lần thì khóa
   password_lock_time 0.0003472        -- Khóa 30s
   password_life_time 90               -- Mật khẩu hết hạn sau 90 ngày
   sessions_per_user 3                 -- Tối đa 3 phiên đăng nhập đồng thời
   idle_time 30                        -- Tự ngắt nếu không hoạt động 30 phút
   connect_time 240                    -- Giới hạn thời gian kết nối 4 tiếng
   cpu_per_session unlimited
   cpu_per_call unlimited
   logical_reads_per_session unlimited;

create profile cus_profile limit
   failed_login_attempts 3
   password_lock_time 0.0003472        -- Khóa 30s
   password_life_time 180              -- Khách hàng đổi mật khẩu 6 tháng 1 lần
   sessions_per_user 3                 -- Chỉ 1 phiên đăng nhập duy nhất
   idle_time 15                        -- Hết hoạt động 15 phút -> tự ngắt
   connect_time 120;                    -- Giới hạn 2 tiếng mỗi lần đăng nhập

create profile staff_profile limit
   failed_login_attempts 3
   password_life_time 90
   sessions_per_user 1
   idle_time 30
   password_grace_time 7;

-- =====================================================
--  5. ROLE PHÂN QUYỀN
-- =====================================================
create role role_admin;
create role role_customer;
create role role_staff;

-- Quyền đăng nhập
grant create session to role_admin;
grant create session to role_customer;

-- =====================================================
-- 6. CẤP QUYỀN CHI TIẾT
-- =====================================================

-- ADMIN có toàn quyền
grant all privileges to role_admin;

-- CUSTOMER chỉ có quyền thao tác dữ liệu người dùng và tour
grant select on khachhang to role_customer;
grant select on tour to role_customer;
grant select,insert on dattour to role_customer;
grant select,insert on danhgiatour to role_customer;
grant select,insert on tinnhan to role_customer;
grant select,update on khachhang to role_customer;

-- Chỉ cho phép xem trên dữ liệu
grant select on khachhang to role_read_only;
grant select on tour to role_read_only;
grant select on dattour to role_read_only;

-- Quyền cho nhân viên
grant select,update on tour to role_staff;
grant select,insert on khachhang to role_staff;
grant select,insert on dattour to role_staff;
grant select,insert,update on hoadon to role_staff;
grant create session to role_staff;

-- =====================================================
-- 7. TẠO USER TRONG ORACLE
-- =====================================================
create user admin2 identified by 123456
   profile admin_profile
   default tablespace users
   temporary tablespace temp;

grant role_admin to tadmin;
grant unlimited tablespace to admin2;


create user cus1 identified by 123456
   profile cus_profile
   default tablespace users
   temporary tablespace temp;
grant role_customer to cus1;
grant unlimited tablespace to cus1;

create user staff1 identified by 123456
   profile staff_profile
   default tablespace users
   temporary tablespace temp;
grant role_staff to staff1;

-- 8. Insert Dữ liệu mẫu
-- =====================================================
insert into chinhanh (
   tenchinhanh,
   diachi,
   sodienthoai
) values ( 'Miền Bắc',
           'Số 12 Trần Hưng Đạo, Hà Nội',
           '024-1234567' );

insert into chinhanh (
   tenchinhanh,
   diachi,
   sodienthoai
) values ( 'Miền Trung',
           '45 Lê Lợi, Đà Nẵng',
           '0236-7654321' );

insert into chinhanh (
   tenchinhanh,
   diachi,
   sodienthoai
) values ( 'Miền Nam',
           '120 Nguyễn Huệ, Quận 1, TP.HCM',
           '028-9876543' );
