CREATE TABLE KhachHang (
    MaKhachHang NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HoTen NVARCHAR2(100),
    Email NVARCHAR2(100) UNIQUE NOT NULL,
    SoDienThoai NVARCHAR2(20),
    DiaChi NVARCHAR2(200),
    VaiTro NVARCHAR2(20) DEFAULT 'KhachHang' CHECK (VaiTro IN ('Admin', 'KhachHang')),
    TrangThai NVARCHAR2(20) DEFAULT 'HoatDong' CHECK (TrangThai IN ('HoatDong', 'BiKhoa')),
    NgayTao DATE DEFAULT SYSDATE,
    ORACLE_USERNAME NVARCHAR2(100)
);

-- ==============================================
-- 2️⃣ BẢNG CƠ SỞ DỮ LIỆU DỊCH VỤ & NHÀ CUNG CẤP
-- ==============================================
CREATE TABLE LoaiDichVu (
    MaLoaiDichVu NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenLoaiDichVu NVARCHAR2(100) NOT NULL,
    MoTa NVARCHAR2(300)
);

CREATE TABLE DichVu (
    MaDichVu NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenDichVu NVARCHAR2(150) NOT NULL,
    GiaCoBan NUMBER(12,2),
    MoTa NVARCHAR2(300),
    MaLoaiDichVu NUMBER,
    CONSTRAINT fk_dv_loaidv FOREIGN KEY (MaLoaiDichVu) REFERENCES LoaiDichVu(MaLoaiDichVu)
);

CREATE TABLE NhaCungCap (
    MaNhaCungCap NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenNhaCungCap NVARCHAR2(150) NOT NULL,
    DiaChi NVARCHAR2(200),
    SoDienThoai NVARCHAR2(20),
    Email NVARCHAR2(100),
    Website NVARCHAR2(100)
);

CREATE TABLE NhaCungCap_DichVu (
    MaNhaCungCap NUMBER,
    MaDichVu NUMBER,
    GiaCungUng NUMBER(12,2),
    DieuKien NVARCHAR2(200),
    CONSTRAINT pk_nccdv PRIMARY KEY (MaNhaCungCap, MaDichVu),
    CONSTRAINT fk_nccdv_ncc FOREIGN KEY (MaNhaCungCap) REFERENCES NhaCungCap(MaNhaCungCap),
    CONSTRAINT fk_nccdv_dv FOREIGN KEY (MaDichVu) REFERENCES DichVu(MaDichVu)
);

-- ==============================================
-- 3️⃣ BẢNG TOUR (đã thêm cột QR)
-- ==============================================
CREATE TABLE Tour (
    MaTour NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TieuDe NVARCHAR2(200),
    MoTa NVARCHAR2(500),
    NoiKhoiHanh NVARCHAR2(100),
    NoiDen NVARCHAR2(100),
    ThanhPho NVARCHAR2(100),
    ThoiGian DATE,
    GiaNguoiLon NUMBER(12,2),
    GiaTreEm NUMBER(12,2),
    TrangThai NVARCHAR2(50) DEFAULT 'Hoạt động' CHECK (TrangThai IN ('Hoạt động', 'Tạm ngưng', 'Đã kết thúc', 'Đã hủy', 'Ẩn'));
    SoLuong NUMBER,
    QR NVARCHAR2(500)  
);

CREATE TABLE ChiTietTour (
    MaTour NUMBER,
    MaDichVu NUMBER,
    SoLuong NUMBER,
    CONSTRAINT pk_cttour PRIMARY KEY (MaTour, MaDichVu),
    CONSTRAINT fk_cttour_tour FOREIGN KEY (MaTour) REFERENCES Tour(MaTour),
    CONSTRAINT fk_cttour_dv FOREIGN KEY (MaDichVu) REFERENCES DichVu(MaDichVu)
);

CREATE TABLE AnhTour (
    MaAnh NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTour NUMBER,
    DuongDanAnh NVARCHAR2(300),
    MoTa NVARCHAR2(200),
    NgayTaiLen DATE DEFAULT SYSDATE,
    CONSTRAINT fk_anh_tour FOREIGN KEY (MaTour) REFERENCES Tour(MaTour)
);

CREATE TABLE DatTour (
    MaDatTour NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaKhachHang NUMBER,
    MaTour NUMBER,
    NgayDat DATE DEFAULT SYSDATE,
    SoNguoiLon NUMBER,
    SoTreEm NUMBER,
    TongTien NUMBER(12,2),
    TrangThaiThanhToan NVARCHAR2(20),
    TrangThaiDat NVARCHAR2(20),
    YeuCauDacBiet NVARCHAR2(200),
    CONSTRAINT fk_dattour_kh FOREIGN KEY (MaKhachHang) REFERENCES KhachHang(MaKhachHang),
    CONSTRAINT fk_dattour_tour FOREIGN KEY (MaTour) REFERENCES Tour(MaTour)
);

CREATE TABLE HoaDon (
    MaHoaDon NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaDatTour NUMBER,
    SoTien NUMBER(12,2),
    NgayXuat DATE DEFAULT SYSDATE,
    TrangThai NVARCHAR2(20),
    CONSTRAINT fk_hd_dt FOREIGN KEY (MaDatTour) REFERENCES DatTour(MaDatTour)
);

CREATE TABLE DanhGiaTour (
    MaDanhGia NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaKhachHang NUMBER NOT NULL,
    MaTour NUMBER NOT NULL,
    SoSao NUMBER CHECK (SoSao BETWEEN 1 AND 5),
    NoiDungDanhGia NVARCHAR2(300),
    NgayDanhGia DATE DEFAULT SYSDATE,
    CONSTRAINT fk_dg_kh FOREIGN KEY (MaKhachHang) REFERENCES KhachHang(MaKhachHang),
    CONSTRAINT fk_dg_tour FOREIGN KEY (MaTour) REFERENCES Tour(MaTour)
);

CREATE TABLE TinNhan (
    MaTinNhan NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaKhachHang NUMBER,
    NoiDung NVARCHAR2(500),
    NgayGui DATE DEFAULT SYSDATE,
    DaDoc CHAR(1) DEFAULT 'N',
    CONSTRAINT fk_tn_kh FOREIGN KEY (MaKhachHang) REFERENCES KhachHang(MaKhachHang)
);

CREATE TABLE NhatKyHeThong (
    MaNhatKy NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenBang NVARCHAR2(100),
    HanhDong NVARCHAR2(50),
    ThoiGian DATE DEFAULT SYSDATE,
    NguoiThucHien NVARCHAR2(50)
);


-- =====================================================
-- 🔐 4. PROFILE KIỂM SOÁT ĐĂNG NHẬP
-- =====================================================
CREATE PROFILE admin_profile LIMIT
    FAILED_LOGIN_ATTEMPTS 3             -- Sai mật khẩu 3 lần thì khóa
    PASSWORD_LOCK_TIME 0.0003472        -- Khóa 30s
    PASSWORD_LIFE_TIME 90               -- Mật khẩu hết hạn sau 90 ngày
    SESSIONS_PER_USER 3                 -- Tối đa 3 phiên đăng nhập đồng thời
    IDLE_TIME 30                        -- Tự ngắt nếu không hoạt động 30 phút
    CONNECT_TIME 240                    -- Giới hạn thời gian kết nối 4 tiếng
    CPU_PER_SESSION UNLIMITED
    CPU_PER_CALL UNLIMITED
    LOGICAL_READS_PER_SESSION UNLIMITED;

CREATE PROFILE cus_profile LIMIT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LOCK_TIME 0.0003472        -- Khóa 30s
    PASSWORD_LIFE_TIME 180              -- Khách hàng đổi mật khẩu 6 tháng 1 lần
    SESSIONS_PER_USER 1                 -- Chỉ 1 phiên đăng nhập duy nhất
    IDLE_TIME 15                        -- Hết hoạt động 15 phút -> tự ngắt
    CONNECT_TIME 120;                    -- Giới hạn 2 tiếng mỗi lần đăng nhập
-- =====================================================
-- 🧩 5. ROLE PHÂN QUYỀN
-- =====================================================
CREATE ROLE ROLE_ADMIN;
CREATE ROLE ROLE_CUSTOMER;
CREATE ROLE ROLE_READ_ONLY;

-- Quyền đăng nhập
GRANT CREATE SESSION TO ROLE_ADMIN;
GRANT CREATE SESSION TO ROLE_CUSTOMER;

-- =====================================================
-- 🛠 6. CẤP QUYỀN CHI TIẾT
-- =====================================================

-- ADMIN có toàn quyền
GRANT ALL PRIVILEGES TO ROLE_ADMIN;

-- CUSTOMER chỉ có quyền thao tác dữ liệu người dùng và tour
GRANT SELECT ON KhachHang TO ROLE_CUSTOMER;
GRANT SELECT ON Tour TO ROLE_CUSTOMER;
GRANT SELECT, INSERT ON DatTour TO ROLE_CUSTOMER;
GRANT SELECT, INSERT ON DanhGiaTour TO ROLE_CUSTOMER;
GRANT SELECT, INSERT ON TinNhan TO ROLE_CUSTOMER;
GRANT SELECT, UPDATE ON KhachHang TO ROLE_CUSTOMER;

-- Chỉ cho phép xem trên dữ liệu
GRANT SELECT ON KhachHang TO ROLE_READ_ONLY;
GRANT SELECT ON Tour TO ROLE_READ_ONLY;
GRANT SELECT ON DatTour TO ROLE_READ_ONLY;
GRANT SELECT ON DichVu TO ROLE_READ_ONLY;

-- =====================================================
-- 👥 7. TẠO USER TRONG ORACLE
-- =====================================================
CREATE USER admin1 IDENTIFIED BY 123456
    PROFILE admin_profile
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP;
GRANT ROLE_ADMIN TO admin1;
GRANT UNLIMITED TABLESPACE TO admin1;


CREATE USER cus1 IDENTIFIED BY 123456
    PROFILE cust_profile
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP;
GRANT ROLE_CUSTOMER TO cus1;
GRANT UNLIMITED TABLESPACE TO cus1;

