CREATE TABLE KhachHang (
    MaKhachHang NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HoTen NVARCHAR2(100),
    Email NVARCHAR2(100) UNIQUE NOT NULL,
    SoDienThoai NVARCHAR2(20),
    DiaChi NVARCHAR2(200),
    VaiTro NVARCHAR2(20) DEFAULT 'KhachHang' CHECK (VaiTro IN ('Admin', 'KhachHang','NhanVien')),
    TrangThai NVARCHAR2(20) DEFAULT 'HoatDong' CHECK (TrangThai IN ('HoatDong', 'BiKhoa')),
    NgayTao DATE DEFAULT SYSDATE,
    ORACLE_USERNAME NVARCHAR2(100),
    QR_CODE NVARCHAR2(500)
);

CREATE TABLE NhanVien (
    MaNhanVien NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HoTen NVARCHAR2(100),
    Email NVARCHAR2(100) UNIQUE NOT NULL,
    SoDienThoai NVARCHAR2(20),
    VaiTro NVARCHAR2(20) DEFAULT 'NhanVien' CHECK (VaiTro IN ('Admin', 'NhanVien')),
    TrangThai NVARCHAR2(20) DEFAULT 'HoatDong' CHECK (TrangThai IN ('HoatDong', 'BiKhoa')),
    NgayTao DATE DEFAULT SYSDATE,
    QR_CODE NVARCHAR2(500),
    MaChiNhanh NUMBER,
    ORACLE_USERNAME NVARCHAR2(100),
    CONSTRAINT fk_nv_cn FOREIGN KEY (MaChiNhanh) REFERENCES ChiNhanh(MaChiNhanh);
);
-- ==============================================
-- 2️⃣ BẢNG CƠ SỞ DỮ LIỆU DỊCH VỤ & NHÀ CUNG CẤP
-- ==============================================
CREATE TABLE LoaiDichVu (
    MaLoaiDichVu NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenLoaiDichVu NVARCHAR2(100) NOT NULL,
    MoTa NVARCHAR2(300)
);

CREATE TABLE DichVu (
    MaDichVu NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenDichVu NVARCHAR2(150) NOT NULL,
    GiaCoBan NUMBER(12,2),
    MoTa NVARCHAR2(300),
    MaLoaiDichVu NUMBER,
    CONSTRAINT fk_dv_loaidv FOREIGN KEY (MaLoaiDichVu) REFERENCES LoaiDichVu(MaLoaiDichVu)
);

CREATE TABLE NhaCungCap (
    MaNhaCungCap NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenNhaCungCap NVARCHAR2(150) NOT NULL,
    DiaChi NVARCHAR2(200),
    SoDienThoai NVARCHAR2(20),
    Email NVARCHAR2(100),
    Website NVARCHAR2(100)
);

CREATE TABLE NhaCungCap_DichVu (
    MaNhaCungCap NUMBER,
    MaDichVu NUMBER,
    GiaCungUng NUMBER(12,2),
    DieuKien NVARCHAR2(200),
    CONSTRAINT pk_nccdv PRIMARY KEY (MaNhaCungCap, MaDichVu),
    CONSTRAINT fk_nccdv_ncc FOREIGN KEY (MaNhaCungCap) REFERENCES NhaCungCap(MaNhaCungCap),
    CONSTRAINT fk_nccdv_dv FOREIGN KEY (MaDichVu) REFERENCES DichVu(MaDichVu)
);

CREATE TABLE Tour (
    MaTour NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TieuDe NVARCHAR2(200),
    MoTa NVARCHAR2(500),
    NoiKhoiHanh NVARCHAR2(100),
    NoiDen NVARCHAR2(100),
    ThanhPho NVARCHAR2(100),
    ThoiGian DATE,
    GiaNguoiLon NUMBER(12,2),
    GiaTreEm NUMBER(12,2),
    TrangThai NVARCHAR2(50) DEFAULT 'Hoạt động' CHECK (TrangThai IN ('Hoạt động', 'Tạm ngưng', 'Đã kết thúc', 'Đã hủy', 'Ẩn'));
    SoLuong NUMBER,
    QR NVARCHAR2(500),
    MaChiNhanh NUMBER,
    ChiNhanh NVARCHAR2(100),
    CONSTRAINT fk_tour_cn FOREIGN KEY (MaChiNhanh) REFERENCES ChiNhanh(MaChiNhanh);
);

CREATE TABLE ChiTietTour (
    MaTour NUMBER,
    MaDichVu NUMBER,
    SoLuong NUMBER,
    CONSTRAINT pk_cttour PRIMARY KEY (MaTour, MaDichVu),
    CONSTRAINT fk_cttour_tour FOREIGN KEY (MaTour) REFERENCES Tour(MaTour),
    CONSTRAINT fk_cttour_dv FOREIGN KEY (MaDichVu) REFERENCES DichVu(MaDichVu)
);

CREATE TABLE AnhTour (
    MaAnh NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTour NUMBER,
    DuongDanAnh NVARCHAR2(300),
    MoTa NVARCHAR2(200),
    NgayTaiLen DATE DEFAULT SYSDATE,
    CONSTRAINT fk_anh_tour FOREIGN KEY (MaTour) REFERENCES Tour(MaTour)
);

CREATE TABLE DatTour (
    MaDatTour NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaKhachHang NUMBER,
    MaTour NUMBER,
    NgayDat DATE DEFAULT SYSDATE,
    SoNguoiLon NUMBER,
    SoTreEm NUMBER,
    TongTien NUMBER(12,2),
    TrangThaiThanhToan NVARCHAR2(20),
    TrangThaiDat NVARCHAR2(20),
    YeuCauDacBiet NVARCHAR2(200),
    CONSTRAINT fk_dattour_kh FOREIGN KEY (MaKhachHang) REFERENCES KhachHang(MaKhachHang),
    CONSTRAINT fk_dattour_tour FOREIGN KEY (MaTour) REFERENCES Tour(MaTour)
);

CREATE TABLE HoaDon (
    MaHoaDon NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaDatTour NUMBER,
    SoTien NUMBER(12,2),
    NgayXuat DATE DEFAULT SYSDATE,
    TrangThai NVARCHAR2(20),
    ChuKySo NVARCHAR2(500),
    CONSTRAINT fk_hd_dt FOREIGN KEY (MaDatTour) REFERENCES DatTour(MaDatTour)
);

CREATE TABLE DanhGiaTour (
    MaDanhGia NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaKhachHang NUMBER NOT NULL,
    MaTour NUMBER NOT NULL,
    SoSao NUMBER CHECK (SoSao BETWEEN 1 AND 5),
    NoiDungDanhGia NVARCHAR2(300),
    NgayDanhGia DATE DEFAULT SYSDATE,
    CONSTRAINT fk_dg_kh FOREIGN KEY (MaKhachHang) REFERENCES KhachHang(MaKhachHang),
    CONSTRAINT fk_dg_tour FOREIGN KEY (MaTour) REFERENCES Tour(MaTour)
);

CREATE TABLE TinNhan (
    MaTinNhan NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaKhachHang NUMBER,
    NoiDung NVARCHAR2(500),
    NgayGui DATE DEFAULT SYSDATE,
    DaDoc CHAR(1) DEFAULT 'N',
    CONSTRAINT fk_tn_kh FOREIGN KEY (MaKhachHang) REFERENCES KhachHang(MaKhachHang)
);

CREATE TABLE NhatKyHeThong (
    MaNhatKy NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenBang NVARCHAR2(100),
    HanhDong NVARCHAR2(50),
    ThoiGian DATE DEFAULT SYSDATE,
    NguoiThucHien NVARCHAR2(50)
);

CREATE TABLE QR_Login (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SessionKey NVARCHAR2(100) UNIQUE,
    UserId NUMBER,
    IsUsed NUMBER(1) DEFAULT 0,
    CreatedAt DATE DEFAULT SYSDATE,
    CONSTRAINT fk_qr_user FOREIGN KEY (UserId) REFERENCES KhachHang(MaKhachHang)
);
CREATE TABLE ChiNhanh (
    MaChiNhanh NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenChiNhanh NVARCHAR2(100) NOT NULL,
    DiaChi NVARCHAR2(200),
    SoDienThoai NVARCHAR2(20)
);

CREATE TABLE TADMIN.USER_SESSIONS (
    SESSION_ID VARCHAR2(64) PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    USER_TYPE NVARCHAR2(20) NOT NULL,
    DEVICE_TYPE NVARCHAR2(10) DEFAULT 'WEB' NOT NULL,
    LOGIN_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_ACTIVITY TIMESTAMP DEFAULT SYSTIMESTAMP,
    IP_ADDRESS NVARCHAR2(50),
    DEVICE_INFO NVARCHAR2(200),
    IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL
);

CREATE INDEX IDX_USER_SESSION_STATUS ON TADMIN.USER_SESSIONS (USER_ID, USER_TYPE, IS_ACTIVE);

-- =====================================================
-- 🔐 4. PROFILE KIỂM SOÁT ĐĂNG NHẬP
-- =====================================================
CREATE PROFILE admin_profile LIMIT
    FAILED_LOGIN_ATTEMPTS 3             -- Sai mật khẩu 3 lần thì khóa
    PASSWORD_LOCK_TIME 0.0003472        -- Khóa 30s
    PASSWORD_LIFE_TIME 90               -- Mật khẩu hết hạn sau 90 ngày
    SESSIONS_PER_USER 3                 -- Tối đa 3 phiên đăng nhập đồng thời
    IDLE_TIME 30                        -- Tự ngắt nếu không hoạt động 30 phút
    CONNECT_TIME 240                    -- Giới hạn thời gian kết nối 4 tiếng
    CPU_PER_SESSION UNLIMITED
    CPU_PER_CALL UNLIMITED
    LOGICAL_READS_PER_SESSION UNLIMITED;

CREATE PROFILE cus_profile LIMIT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LOCK_TIME 0.0003472        -- Khóa 30s
    PASSWORD_LIFE_TIME 180              -- Khách hàng đổi mật khẩu 6 tháng 1 lần
    SESSIONS_PER_USER 3                 -- Chỉ 1 phiên đăng nhập duy nhất
    IDLE_TIME 15                        -- Hết hoạt động 15 phút -> tự ngắt
    CONNECT_TIME 120;                    -- Giới hạn 2 tiếng mỗi lần đăng nhập

CREATE PROFILE staff_profile LIMIT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 90
    SESSIONS_PER_USER 1
    IDLE_TIME 30
    PASSWORD_GRACE_TIME 7;

-- =====================================================
-- 🧩 5. ROLE PHÂN QUYỀN
-- =====================================================
CREATE ROLE ROLE_ADMIN;
CREATE ROLE ROLE_CUSTOMER;
CREATE ROLE ROLE_STAFF;
CREATE ROLE ROLE_READ_ONLY;

-- Quyền đăng nhập
GRANT CREATE SESSION TO ROLE_ADMIN;
GRANT CREATE SESSION TO ROLE_CUSTOMER;

-- =====================================================
-- 🛠 6. CẤP QUYỀN CHI TIẾT
-- =====================================================

-- ADMIN có toàn quyền
GRANT ALL PRIVILEGES TO ROLE_ADMIN;

-- CUSTOMER chỉ có quyền thao tác dữ liệu người dùng và tour
GRANT SELECT ON KhachHang TO ROLE_CUSTOMER;
GRANT SELECT ON Tour TO ROLE_CUSTOMER;
GRANT SELECT, INSERT ON DatTour TO ROLE_CUSTOMER;
GRANT SELECT, INSERT ON DanhGiaTour TO ROLE_CUSTOMER;
GRANT SELECT, INSERT ON TinNhan TO ROLE_CUSTOMER;
GRANT SELECT, UPDATE ON KhachHang TO ROLE_CUSTOMER;

-- Chỉ cho phép xem trên dữ liệu
GRANT SELECT ON KhachHang TO ROLE_READ_ONLY;
GRANT SELECT ON Tour TO ROLE_READ_ONLY;
GRANT SELECT ON DatTour TO ROLE_READ_ONLY;
GRANT SELECT ON DichVu TO ROLE_READ_ONLY;

-- Quyền cho nhân viên
GRANT SELECT, UPDATE ON Tour TO ROLE_STAFF;
GRANT SELECT, UPDATE ON DichVu TO ROLE_STAFF;
GRANT SELECT, INSERT ON KhachHang TO ROLE_STAFF;
GRANT SELECT, INSERT ON DatTour TO ROLE_STAFF;
GRANT SELECT, INSERT, UPDATE ON HoaDon TO ROLE_STAFF;
GRANT CREATE SESSION TO ROLE_STAFF;

-- =====================================================
-- 👥 7. TẠO USER TRONG ORACLE
-- =====================================================
CREATE USER admin2 IDENTIFIED BY 123456
  PROFILE admin_profile
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP;

GRANT ROLE_ADMIN TO admin2;
GRANT UNLIMITED TABLESPACE TO admin2;


CREATE USER cus1 IDENTIFIED BY 123456
    PROFILE cust_profile
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP;
GRANT ROLE_CUSTOMER TO cus1;
GRANT UNLIMITED TABLESPACE TO cus1;

CREATE USER staff1 IDENTIFIED BY 123456
    PROFILE staff_profile
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP;
GRANT ROLE_STAFF TO staff1;

-- =====================================================
-- 👥 8. VPD và Trigger cần thiết
-- =====================================================
-- Bước 1: Tạo Context và Package để quản lý MaChiNhanh

-- Tạo một context để lưu trữ mã chi nhánh của người dùng
CREATE OR REPLACE CONTEXT tour_management_ctx USING TADMIN.pkg_tour_management;
/

-- Tạo package để set giá trị cho context
CREATE OR REPLACE PACKAGE TADMIN.pkg_tour_management AS
  -- Thủ tục này sẽ được gọi từ ứng dụng ASP.NET để gán mã chi nhánh
  PROCEDURE set_branch_id(branch_id IN NUMBER);
END pkg_tour_management;
/

CREATE OR REPLACE PACKAGE BODY TADMIN.pkg_tour_management AS
  PROCEDURE set_branch_id(branch_id IN NUMBER) IS
  BEGIN
    -- Gán giá trị branch_id vào context 'tour_management_ctx'
    DBMS_SESSION.SET_CONTEXT('tour_management_ctx', 'branch_id', branch_id);
  END set_branch_id;
END pkg_tour_management;
/
-- Bước 2: Tạo hàm chính sách (Policy Function)

-- Hàm này sẽ được Oracle tự động gọi mỗi khi có truy vấn đến bảng TOUR.
-- Nó sẽ trả về một mệnh đề WHERE để lọc dữ liệu dựa trên mã chi nhánh trong context.
CREATE OR REPLACE FUNCTION TADMIN.fn_vpd_tour_security(
  schema_name IN VARCHAR2,
  table_name IN VARCHAR2
)
RETURN VARCHAR2
AS
  v_branch_id VARCHAR2(100);
BEGIN
  -- Lấy mã chi nhánh từ context mà ứng dụng đã set
  v_branch_id := SYS_CONTEXT('tour_management_ctx', 'branch_id');

  -- Nếu người dùng là ADMIN hoặc một vai trò không phải nhân viên,
  -- context sẽ không được set, và họ sẽ thấy tất cả các tour.
  IF v_branch_id IS NULL THEN
    RETURN '1=1'; -- Trả về điều kiện luôn đúng (thấy tất cả)
  END IF;

  -- Nếu là nhân viên, chỉ thấy các tour thuộc chi nhánh của họ.
  RETURN 'MaChiNhanh = ' || v_branch_id;
END;
/
-- Bước 3: Gán chính sách VPD vào bảng TOUR (cách tiếp cận mới)

-- Thử nghiệm bằng cách thêm tham số update_check và để statement_types mặc định
BEGIN
  DBMS_RLS.ADD_POLICY(
    object_schema   => 'TADMIN',
    object_name     => 'TOUR',
    policy_name     => 'tour_branch_policy',
    function_schema => 'TADMIN',
    policy_function => 'fn_vpd_tour_security',
    update_check    => TRUE
  );
END;
/
-- Bước 4: Tạo lại Trigger để tự động gán chi nhánh khi tạo tour

CREATE OR REPLACE TRIGGER TADMIN.trg_tour_branch_autofill
BEFORE INSERT ON TADMIN.TOUR
FOR EACH ROW
DECLARE
  v_branch_id NUMBER;
BEGIN
  -- Lấy mã chi nhánh từ context mà ứng dụng đã set
  v_branch_id := TO_NUMBER(SYS_CONTEXT('tour_management_ctx', 'branch_id'));

  -- Nếu mã chi nhánh tồn tại trong context, gán nó cho tour mới
  IF v_branch_id IS NOT NULL THEN
    :NEW.MaChiNhanh := v_branch_id;
  END IF;
EXCEPTION
  -- Bỏ qua lỗi nếu context không được set hoặc không phải là số
  WHEN OTHERS THEN
    NULL;
END;
/
--- Cập nhật VPD để phân quyền theo vai trò và chi nhánh
-- Cập nhật package và hàm chính sách để xử lý theo vai trò

-- Cập nhật package để có thể set cả vai trò và chi nhánh
CREATE OR REPLACE PACKAGE TADMIN.pkg_tour_management AS
  PROCEDURE set_user_context(role_name IN VARCHAR2, branch_id IN NUMBER);
END pkg_tour_management;
/

CREATE OR REPLACE PACKAGE BODY TADMIN.pkg_tour_management AS
  PROCEDURE set_user_context(role_name IN VARCHAR2, branch_id IN NUMBER) IS
  BEGIN
    DBMS_SESSION.SET_CONTEXT('tour_management_ctx', 'role', role_name);
    DBMS_SESSION.SET_CONTEXT('tour_management_ctx', 'branch_id', branch_id);
  END set_user_context;
END pkg_tour_management;
/

-- Cập nhật hàm chính sách để kiểm tra vai trò
CREATE OR REPLACE FUNCTION TADMIN.fn_vpd_tour_security(
  schema_name IN VARCHAR2,
  table_name IN VARCHAR2
)
RETURN VARCHAR2
AS
  v_role VARCHAR2(100);
  v_branch_id VARCHAR2(100);
BEGIN
  v_role := SYS_CONTEXT('tour_management_ctx', 'role');
  v_branch_id := SYS_CONTEXT('tour_management_ctx', 'branch_id');

  -- Admin và Customer có thể thấy tất cả tour
  IF v_role = 'ROLE_ADMIN' OR v_role = 'ROLE_CUSTOMER' THEN
    RETURN '1=1'; 
  -- Nhân viên chỉ thấy tour thuộc chi nhánh của họ
  ELSIF v_role = 'ROLE_STAFF' AND v_branch_id IS NOT NULL THEN
    RETURN 'MaChiNhanh = ' || v_branch_id;
  -- Nếu không có vai trò hoặc là vai trò khác, không thấy gì cả
  ELSE
    RETURN '1=0';
  END IF;
END;
/


-- 👥 9. Insert Dữ liệu mẫu
-- =====================================================
INSERT INTO ChiNhanh (TenChiNhanh, DiaChi, SoDienThoai)
VALUES ('Miền Bắc', 'Số 12 Trần Hưng Đạo, Hà Nội', '024-1234567');

INSERT INTO ChiNhanh (TenChiNhanh, DiaChi, SoDienThoai)
VALUES ('Miền Trung', '45 Lê Lợi, Đà Nẵng', '0236-7654321');

INSERT INTO ChiNhanh (TenChiNhanh, DiaChi, SoDienThoai)
VALUES ('Miền Nam', '120 Nguyễn Huệ, Quận 1, TP.HCM', '028-9876543');


