-- =================================================================================
-- FILE: setup_full_audit.sql
-- DESCRIPTION: Script to set up a comprehensive audit system using three methods.
-- SCHEMA: TADMIN
-- =================================================================================
-- Ghi chú: Vui lòng chạy script này với user có đủ quyền hạn (ví dụ: SYS as SYSDBA)
-- sau khi đã chạy file cleanup_audit.sql.

-- =================================================================================
-- PHẦN 1: CÀI ĐẶT STANDARD AUDITING
-- =================================================================================
-- Mô tả: Bật audit chuẩn cho các hành động INSERT, UPDATE, DELETE.
-- Kết quả được ghi vào UNIFIED_AUDIT_TRAIL.
-- =================================================================================
AUDIT INSERT, UPDATE, DELETE ON TADMIN.HoaDon BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON TADMIN.DatTour BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON TADMIN.NhanVien BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON TADMIN.Tour BY ACCESS;

-- =================================================================================
-- PHẦN 2: CÀI ĐẶT FINE-GRAINED AUDITING (FGA)
-- =================================================================================
-- Mô tả: Bật audit chi tiết (FGA) để ghi lại cả câu lệnh SQL.
-- Kết quả cũng được ghi vào UNIFIED_AUDIT_TRAIL.
-- =================================================================================
BEGIN
  DBMS_FGA.ADD_POLICY(
    object_schema   => 'TADMIN',
    object_name     => 'HoaDon',
    policy_name     => 'FGA_HOADON_POLICY',
    statement_types => 'INSERT,UPDATE,DELETE'
    audit_column_opts => DBMS_FGA.ALL_COLUMNS,
    audit_trail       => DBMS_FGA.DB_EXTENDED
  );
END;
/
BEGIN
  DBMS_FGA.ADD_POLICY(
    object_schema   => 'TADMIN',
    object_name     => 'DatTour',
    policy_name     => 'FGA_DATTUOR_POLICY',
    statement_types => 'INSERT,UPDATE,DELETE'
    audit_column_opts => DBMS_FGA.ALL_COLUMNS,
    audit_trail       => DBMS_FGA.DB_EXTENDED
  );
END;
/
BEGIN
  DBMS_FGA.ADD_POLICY(
    object_schema   => 'TADMIN',
    object_name     => 'NhanVien',
    policy_name     => 'FGA_NHANVIEN_POLICY',
    statement_types => 'INSERT,UPDATE,DELETE'
    audit_column_opts => DBMS_FGA.ALL_COLUMNS,
    audit_trail       => DBMS_FGA.DB_EXTENDED
  );
END;
/
DBMS_FGA.ADD_POLICY(
  object_schema   => 'TADMIN',
  object_name     => 'Tour', -- và tương tự cho HoaDon, DatTour, NhanVien
  policy_name     => 'FGA_TOUR_POLICY',
  statement_types => 'INSERT,UPDATE,DELETE',
  audit_column_opts => DBMS_FGA.ALL_COLUMNS,
  audit_trail       => DBMS_FGA.DB_EXTENDED
);

END;
/

-- =================================================================================
-- PHẦN 3: CÀI ĐẶT TRIGGER-BASED AUDITING
-- =================================================================================
-- Mô tả: Cung cấp thông tin chi tiết nhất về giá trị cũ và mới.
-- FIX: So sánh NULL chính xác. Bỏ cột người thực hiện.
-- =================================================================================

-- Bước 3.1: Tạo bảng để lưu trữ log chi tiết
CREATE TABLE TADMIN.AUDIT_LOG_DETAIL (
    LogId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TableName NVARCHAR2(100),
    Action NVARCHAR2(20),
    ActionTimestamp TIMESTAMP DEFAULT SYSTIMESTAMP,
    RecordId NVARCHAR2(100),
    OldValues CLOB,
    NewValues CLOB,
    CONSTRAINT chk_action_v4 CHECK (Action IN ('INSERT', 'UPDATE', 'DELETE'))
);
/

-- Bước 3.2: Tạo trigger cho bảng NhanVien
CREATE OR REPLACE TRIGGER TADMIN.TRG_AUDIT_NHANVIEN
AFTER INSERT OR UPDATE OR DELETE ON TADMIN.NhanVien
FOR EACH ROW
DECLARE
    v_action NVARCHAR2(20);
    v_record_id NVARCHAR2(100);
    v_old_values CLOB := '{}';
    v_new_values CLOB := '{}';
BEGIN
    v_action := CASE WHEN INSERTING THEN 'INSERT' WHEN UPDATING THEN 'UPDATE' WHEN DELETING THEN 'DELETE' END;

    IF v_action = 'DELETE' THEN
        v_record_id := :OLD.MaNhanVien;
    ELSE
        v_record_id := :NEW.MaNhanVien;
    END IF;

    IF v_action = 'INSERT' THEN
        v_new_values := JSON_OBJECT('MANHANVIEN' VALUE :NEW.MANHANVIEN, 'HOTEN' VALUE :NEW.HOTEN, 'EMAIL' VALUE :NEW.EMAIL, 'VAITRO' VALUE :NEW.VAITRO, 'TRANGTHAI' VALUE :NEW.TRANGTHAI, 'MACHINHANH' VALUE :NEW.MACHINHANH);
    ELSIF v_action = 'UPDATE' THEN
        DECLARE
            json_obj_old JSON_OBJECT_T := JSON_OBJECT_T();
            json_obj_new JSON_OBJECT_T := JSON_OBJECT_T();
        BEGIN
            IF (:OLD.HOTEN <> :NEW.HOTEN OR (:OLD.HOTEN IS NULL AND :NEW.HOTEN IS NOT NULL) OR (:OLD.HOTEN IS NOT NULL AND :NEW.HOTEN IS NULL)) THEN json_obj_old.put('HOTEN', :OLD.HOTEN); json_obj_new.put('HOTEN', :NEW.HOTEN); END IF;
            IF (:OLD.EMAIL <> :NEW.EMAIL OR (:OLD.EMAIL IS NULL AND :NEW.EMAIL IS NOT NULL) OR (:OLD.EMAIL IS NOT NULL AND :NEW.EMAIL IS NULL)) THEN json_obj_old.put('EMAIL', :OLD.EMAIL); json_obj_new.put('EMAIL', :NEW.EMAIL); END IF;
            IF (:OLD.SODIENTHOAI <> :NEW.SODIENTHOAI OR (:OLD.SODIENTHOAI IS NULL AND :NEW.SODIENTHOAI IS NOT NULL) OR (:OLD.SODIENTHOAI IS NOT NULL AND :NEW.SODIENTHOAI IS NULL)) THEN json_obj_old.put('SODIENTHOAI', :OLD.SODIENTHOAI); json_obj_new.put('SODIENTHOAI', :NEW.SODIENTHOAI); END IF;
            IF (:OLD.VAITRO <> :NEW.VAITRO OR (:OLD.VAITRO IS NULL AND :NEW.VAITRO IS NOT NULL) OR (:OLD.VAITRO IS NOT NULL AND :NEW.VAITRO IS NULL)) THEN json_obj_old.put('VAITRO', :OLD.VAITRO); json_obj_new.put('VAITRO', :NEW.VAITRO); END IF;
            IF (:OLD.TRANGTHAI <> :NEW.TRANGTHAI OR (:OLD.TRANGTHAI IS NULL AND :NEW.TRANGTHAI IS NOT NULL) OR (:OLD.TRANGTHAI IS NOT NULL AND :NEW.TRANGTHAI IS NULL)) THEN json_obj_old.put('TRANGTHAI', :OLD.TRANGTHAI); json_obj_new.put('TRANGTHAI', :NEW.TRANGTHAI); END IF;
            IF (:OLD.MACHINHANH <> :NEW.MACHINHANH OR (:OLD.MACHINHANH IS NULL AND :NEW.MACHINHANH IS NOT NULL) OR (:OLD.MACHINHANH IS NOT NULL AND :NEW.MACHINHANH IS NULL)) THEN json_obj_old.put('MACHINHANH', :OLD.MACHINHANH); json_obj_new.put('MACHINHANH', :NEW.MACHINHANH); END IF;
            v_old_values := json_obj_old.to_clob();
            v_new_values := json_obj_new.to_clob();
        END;
    END IF;

    IF v_action IN ('INSERT', 'DELETE') OR (v_action = 'UPDATE' AND v_old_values != '{}') THEN
        INSERT INTO TADMIN.AUDIT_LOG_DETAIL (TableName, Action, RecordId, OldValues, NewValues)
        VALUES ('NhanVien', v_action, v_record_id, v_old_values, v_new_values);
    END IF;
END;
/

-- Trigger cho bảng HoaDon
CREATE OR REPLACE TRIGGER TADMIN.TRG_AUDIT_HOADON
AFTER INSERT OR UPDATE OR DELETE ON TADMIN.HoaDon
FOR EACH ROW
DECLARE
    v_action NVARCHAR2(20);
    v_record_id NVARCHAR2(100);
    v_old_values CLOB := '{}';
    v_new_values CLOB := '{}';
BEGIN
    v_action := CASE WHEN INSERTING THEN 'INSERT' WHEN UPDATING THEN 'UPDATE' WHEN DELETING THEN 'DELETE' END;

    IF v_action = 'DELETE' THEN
        v_record_id := :OLD.MaHoaDon;
    ELSE
        v_record_id := :NEW.MaHoaDon;
    END IF;

    IF v_action = 'INSERT' THEN
        v_new_values := JSON_OBJECT('MAHOADON' VALUE :NEW.MAHOADON, 'MADATTOUR' VALUE :NEW.MADATTOUR, 'SOTIEN' VALUE :NEW.SOTIEN, 'TRANGTHAI' VALUE :NEW.TRANGTHAI);
    ELSIF v_action = 'UPDATE' THEN
        DECLARE
            json_obj_old JSON_OBJECT_T := JSON_OBJECT_T();
            json_obj_new JSON_OBJECT_T := JSON_OBJECT_T();
        BEGIN
            IF (:OLD.SOTIEN <> :NEW.SOTIEN OR (:OLD.SOTIEN IS NULL AND :NEW.SOTIEN IS NOT NULL) OR (:OLD.SOTIEN IS NOT NULL AND :NEW.SOTIEN IS NULL)) THEN json_obj_old.put('SOTIEN', :OLD.SOTIEN); json_obj_new.put('SOTIEN', :NEW.SOTIEN); END IF;
            IF (:OLD.TRANGTHAI <> :NEW.TRANGTHAI OR (:OLD.TRANGTHAI IS NULL AND :NEW.TRANGTHAI IS NOT NULL) OR (:OLD.TRANGTHAI IS NOT NULL AND :NEW.TRANGTHAI IS NULL)) THEN json_obj_old.put('TRANGTHAI', :OLD.TRANGTHAI); json_obj_new.put('TRANGTHAI', :NEW.TRANGTHAI); END IF;
            v_old_values := json_obj_old.to_clob();
            v_new_values := json_obj_new.to_clob();
        END;
    END IF;

    IF v_action IN ('INSERT', 'DELETE') OR (v_action = 'UPDATE' AND v_old_values != '{}') THEN
        INSERT INTO TADMIN.AUDIT_LOG_DETAIL (TableName, Action, RecordId, OldValues, NewValues)
        VALUES ('HoaDon', v_action, v_record_id, v_old_values, v_new_values);
    END IF;
END;
/

-- Trigger cho bảng Tour
CREATE OR REPLACE TRIGGER TADMIN.TRG_AUDIT_TOUR
AFTER INSERT OR UPDATE OR DELETE ON TADMIN.Tour
FOR EACH ROW
DECLARE
    v_action NVARCHAR2(20);
    v_record_id NVARCHAR2(100);
    v_old_values CLOB := '{}';
    v_new_values CLOB := '{}';
BEGIN
    v_action := CASE WHEN INSERTING THEN 'INSERT' WHEN UPDATING THEN 'UPDATE' WHEN DELETING THEN 'DELETE' END;

    IF v_action = 'DELETE' THEN
        v_record_id := :OLD.MaTour;
    ELSE
        v_record_id := :NEW.MaTour;
    END IF;

    IF v_action = 'INSERT' THEN
        v_new_values := JSON_OBJECT('MATOUR' VALUE :NEW.MATOUR, 'TIEUDE' VALUE :NEW.TIEUDE, 'GIANGUOILON' VALUE :NEW.GIANGUOILON, 'TRANGTHAI' VALUE :NEW.TRANGTHAI);
    ELSIF v_action = 'UPDATE' THEN
        DECLARE
            json_obj_old JSON_OBJECT_T := JSON_OBJECT_T();
            json_obj_new JSON_OBJECT_T := JSON_OBJECT_T();
        BEGIN
            IF (:OLD.TIEUDE <> :NEW.TIEUDE OR (:OLD.TIEUDE IS NULL AND :NEW.TIEUDE IS NOT NULL) OR (:OLD.TIEUDE IS NOT NULL AND :NEW.TIEUDE IS NULL)) THEN json_obj_old.put('TIEUDE', :OLD.TIEUDE); json_obj_new.put('TIEUDE', :NEW.TIEUDE); END IF;
            IF (:OLD.GIANGUOILON <> :NEW.GIANGUOILON OR (:OLD.GIANGUOILON IS NULL AND :NEW.GIANGUOILON IS NOT NULL) OR (:OLD.GIANGUOILON IS NOT NULL AND :NEW.GIANGUOILON IS NULL)) THEN json_obj_old.put('GIANGUOILON', :OLD.GIANGUOILON); json_obj_new.put('GIANGUOILON', :NEW.GIANGUOILON); END IF;
            IF (:OLD.GIATREEM <> :NEW.GIATREEM OR (:OLD.GIATREEM IS NULL AND :NEW.GIATREEM IS NOT NULL) OR (:OLD.GIATREEM IS NOT NULL AND :NEW.GIATREEM IS NULL)) THEN json_obj_old.put('GIATREEM', :OLD.GIATREEM); json_obj_new.put('GIATREEM', :NEW.GIATREEM); END IF;
            IF (:OLD.TRANGTHAI <> :NEW.TRANGTHAI OR (:OLD.TRANGTHAI IS NULL AND :NEW.TRANGTHAI IS NOT NULL) OR (:OLD.TRANGTHAI IS NOT NULL AND :NEW.TRANGTHAI IS NULL)) THEN json_obj_old.put('TRANGTHAI', :OLD.TRANGTHAI); json_obj_new.put('TRANGTHAI', :NEW.TRANGTHAI); END IF;
            IF (:OLD.SOLUONG <> :NEW.SOLUONG OR (:OLD.SOLUONG IS NULL AND :NEW.SOLUONG IS NOT NULL) OR (:OLD.SOLUONG IS NOT NULL AND :NEW.SOLUONG IS NULL)) THEN json_obj_old.put('SOLUONG', :OLD.SOLUONG); json_obj_new.put('SOLUONG', :NEW.SOLUONG); END IF;
            v_old_values := json_obj_old.to_clob();
            v_new_values := json_obj_new.to_clob();
        END;
    END IF;

    IF v_action IN ('INSERT', 'DELETE') OR (v_action = 'UPDATE' AND v_old_values != '{}') THEN
        INSERT INTO TADMIN.AUDIT_LOG_DETAIL (TableName, Action, RecordId, OldValues, NewValues)
        VALUES ('Tour', v_action, v_record_id, v_old_values, v_new_values);
    END IF;
END;
/

-- Trigger cho bảng DatTour
CREATE OR REPLACE TRIGGER TADMIN.TRG_AUDIT_DATTOUR
AFTER INSERT OR UPDATE OR DELETE ON TADMIN.DatTour
FOR EACH ROW
DECLARE
    v_action NVARCHAR2(20);
    v_record_id NVARCHAR2(100);
    v_old_values CLOB := '{}';
    v_new_values CLOB := '{}';
BEGIN
    v_action := CASE WHEN INSERTING THEN 'INSERT' WHEN UPDATING THEN 'UPDATE' WHEN DELETING THEN 'DELETE' END;

    IF v_action = 'DELETE' THEN
        v_record_id := :OLD.MaDatTour;
    ELSE
        v_record_id := :NEW.MaDatTour;
    END IF;

    IF v_action = 'INSERT' THEN
        v_new_values := JSON_OBJECT('MADATTOUR' VALUE :NEW.MADATTOUR, 'TONGTIEN' VALUE :NEW.TONGTIEN, 'TRANGTHAITHANHTOAN' VALUE :NEW.TRANGTHAITHANHTOAN, 'TRANGTHAIDAT' VALUE :NEW.TRANGTHAIDAT);
    ELSIF v_action = 'UPDATE' THEN
        DECLARE
            json_obj_old JSON_OBJECT_T := JSON_OBJECT_T();
            json_obj_new JSON_OBJECT_T := JSON_OBJECT_T();
        BEGIN
            IF (:OLD.TONGTIEN <> :NEW.TONGTIEN OR (:OLD.TONGTIEN IS NULL AND :NEW.TONGTIEN IS NOT NULL) OR (:OLD.TONGTIEN IS NOT NULL AND :NEW.TONGTIEN IS NULL)) THEN json_obj_old.put('TONGTIEN', :OLD.TONGTIEN); json_obj_new.put('TONGTIEN', :NEW.TONGTIEN); END IF;
            IF (:OLD.TRANGTHAITHANHTOAN <> :NEW.TRANGTHAITHANHTOAN OR (:OLD.TRANGTHAITHANHTOAN IS NULL AND :NEW.TRANGTHAITHANHTOAN IS NOT NULL) OR (:OLD.TRANGTHAITHANHTOAN IS NOT NULL AND :NEW.TRANGTHAITHANHTOAN IS NULL)) THEN json_obj_old.put('TRANGTHAITHANHTOAN', :OLD.TRANGTHAITHANHTOAN); json_obj_new.put('TRANGTHAITHANHTOAN', :NEW.TRANGTHAITHANHTOAN); END IF;
            IF (:OLD.TRANGTHAIDAT <> :NEW.TRANGTHAIDAT OR (:OLD.TRANGTHAIDAT IS NULL AND :NEW.TRANGTHAIDAT IS NOT NULL) OR (:OLD.TRANGTHAIDAT IS NOT NULL AND :NEW.TRANGTHAIDAT IS NULL)) THEN json_obj_old.put('TRANGTHAIDAT', :OLD.TRANGTHAIDAT); json_obj_new.put('TRANGTHAIDAT', :NEW.TRANGTHAIDAT); END IF;
            v_old_values := json_obj_old.to_clob();
            v_new_values := json_obj_new.to_clob();
        END;
    END IF;

    IF v_action IN ('INSERT', 'DELETE') OR (v_action = 'UPDATE' AND v_old_values != '{}') THEN
        INSERT INTO TADMIN.AUDIT_LOG_DETAIL (TableName, Action, RecordId, OldValues, NewValues)
        VALUES ('DatTour', v_action, v_record_id, v_old_values, v_new_values);
    END IF;
END;
/

PROMPT Full audit setup script finished.
