-- =================================================================================
-- FILE: setup_auditing.sql
-- DESCRIPTION: Script to set up Trigger-based Auditing with improved change tracking.
-- SCHEMA: TADMIN
-- VERSION: 3
-- =================================================================================
-- Ghi chú: Vui lòng chạy script này với user có đủ quyền hạn (ví dụ: SYS as SYSDBA)
-- để tạo các đối tượng cần thiết trong schema TADMIN.

-- =================================================================================
-- PHẦN 1: DỌN DẸP CÁC TRIGGER CŨ
-- =================================================================================
BEGIN
   FOR t IN (SELECT trigger_name FROM all_triggers WHERE owner = 'TADMIN' AND trigger_name IN ('TRG_AUDIT_HOADON', 'TRG_AUDIT_NHANVIEN', 'TRG_AUDIT_TOUR', 'TRG_AUDIT_DATTOUR')) LOOP
      EXECUTE IMMEDIATE 'DROP TRIGGER TADMIN.' || t.trigger_name;
   END LOOP;
END;
/

-- =================================================================================
-- PHẦN 2: TẠO BẢNG AUDIT VÀ PROCEDURE TRUY VẤN
-- =================================================================================
-- Bước 2.1: Tạo bảng để lưu trữ log chi tiết (nếu chưa tồn tại)
/*
CREATE TABLE TADMIN.AUDIT_LOG_DETAIL (
    LogId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TableName NVARCHAR2(100),
    Action NVARCHAR2(20),
    ActionTimestamp TIMESTAMP DEFAULT SYSTIMESTAMP,
    ActionBy NVARCHAR2(100),
    RecordId NVARCHAR2(100),
    OldValues CLOB,
    NewValues CLOB,
    CONSTRAINT chk_action_v3 CHECK (Action IN ('INSERT', 'UPDATE', 'DELETE'))
);
/
*/

-- Bước 2.2: Tạo Procedure để truy vấn dữ liệu audit
CREATE OR REPLACE PROCEDURE TADMIN.GET_AUDIT_LOGS(
    p_table_name IN VARCHAR2,
    p_result OUT SYS_REFCURSOR
)
AS
    v_sql CLOB;
BEGIN
    v_sql := 'SELECT LogId, TableName, Action, ActionTimestamp, ActionBy, RecordId, OldValues, NewValues ' ||
             'FROM TADMIN.AUDIT_LOG_DETAIL ';

    IF p_table_name IS NOT NULL AND LENGTH(p_table_name) > 0 THEN
        IF UPPER(p_table_name) NOT IN ('HOADON', 'NHANVIEN', 'TOUR', 'DATTOUR') THEN
            RAISE_APPLICATION_ERROR(-20001, 'Invalid table name specified for auditing.');
        END IF;
        v_sql := v_sql || 'WHERE UPPER(TableName) = UPPER(:p_table_name) ';
    END IF;

    v_sql := v_sql || 'ORDER BY ActionTimestamp DESC';

    IF p_table_name IS NOT NULL AND LENGTH(p_table_name) > 0 THEN
        OPEN p_result FOR v_sql USING p_table_name;
    ELSE
        OPEN p_result FOR v_sql;
    END IF;
END;
/

-- =================================================================================
-- PHẦN 3: TẠO LẠI CÁC TRIGGER AUDIT (FIX NULL COMPARISON)
-- =================================================================================
-- Mô tả: Sửa lỗi so sánh giá trị NULL, đảm bảo mọi thay đổi đều được ghi lại.
--        Sử dụng DECODE để so sánh, vì DECODE coi hai giá trị NULL là bằng nhau.
-- =================================================================================

-- Trigger cho bảng HoaDon
CREATE OR REPLACE TRIGGER TADMIN.TRG_AUDIT_HOADON
AFTER INSERT OR UPDATE OR DELETE ON TADMIN.HoaDon
FOR EACH ROW
DECLARE
    v_action NVARCHAR2(20);
    v_record_id NVARCHAR2(100);
    v_old_values CLOB := '{}';
    v_new_values CLOB := '{}';
    v_user NVARCHAR2(100);
BEGIN
    v_action := CASE WHEN INSERTING THEN 'INSERT' WHEN UPDATING THEN 'UPDATE' WHEN DELETING THEN 'DELETE' END;
    v_user := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));

    IF v_action = 'DELETE' THEN
        v_record_id := :OLD.MaHoaDon;
        v_old_values := JSON_OBJECT(
            'MAHOADON' VALUE :OLD.MAHOADON, 'MADATTOUR' VALUE :OLD.MADATTOUR, 'SOTIEN' VALUE :OLD.SOTIEN,
            'NGAYXUAT' VALUE TO_CHAR(:OLD.NGAYXUAT, 'YYYY-MM-DD HH24:MI:SS'), 'TRANGTHAI' VALUE :OLD.TRANGTHAI
        );
    ELSE
        v_record_id := :NEW.MaHoaDon;
    END IF;

    IF v_action = 'INSERT' THEN
        v_new_values := JSON_OBJECT(
            'MAHOADON' VALUE :NEW.MAHOADON, 'MADATTOUR' VALUE :NEW.MADATTOUR, 'SOTIEN' VALUE :NEW.SOTIEN,
            'NGAYXUAT' VALUE TO_CHAR(:NEW.NGAYXUAT, 'YYYY-MM-DD HH24:MI:SS'), 'TRANGTHAI' VALUE :NEW.TRANGTHAI
        );
    ELSIF v_action = 'UPDATE' THEN
        DECLARE
            json_obj_old JSON_OBJECT_T := JSON_OBJECT_T();
            json_obj_new JSON_OBJECT_T := JSON_OBJECT_T();
        BEGIN
            IF DECODE(:OLD.MADATTOUR, :NEW.MADATTOUR, 0, 1) = 1 THEN json_obj_old.put('MADATTOUR', :OLD.MADATTOUR); json_obj_new.put('MADATTOUR', :NEW.MADATTOUR); END IF;
            IF DECODE(:OLD.SOTIEN, :NEW.SOTIEN, 0, 1) = 1 THEN json_obj_old.put('SOTIEN', :OLD.SOTIEN); json_obj_new.put('SOTIEN', :NEW.SOTIEN); END IF;
            IF DECODE(:OLD.NGAYXUAT, :NEW.NGAYXUAT, 0, 1) = 1 THEN json_obj_old.put('NGAYXUAT', TO_CHAR(:OLD.NGAYXUAT, 'YYYY-MM-DD HH24:MI:SS')); json_obj_new.put('NGAYXUAT', TO_CHAR(:NEW.NGAYXUAT, 'YYYY-MM-DD HH24:MI:SS')); END IF;
            IF DECODE(:OLD.TRANGTHAI, :NEW.TRANGTHAI, 0, 1) = 1 THEN json_obj_old.put('TRANGTHAI', :OLD.TRANGTHAI); json_obj_new.put('TRANGTHAI', :NEW.TRANGTHAI); END IF;
            v_old_values := json_obj_old.to_clob();
            v_new_values := json_obj_new.to_clob();
        END;
    END IF;

    IF v_action IN ('INSERT', 'DELETE') OR (v_action = 'UPDATE' AND v_old_values != '{}') THEN
        INSERT INTO TADMIN.AUDIT_LOG_DETAIL (TableName, Action, ActionBy, RecordId, OldValues, NewValues)
        VALUES ('HoaDon', v_action, v_user, v_record_id, v_old_values, v_new_values);
    END IF;
END;
/

-- Trigger cho bảng NhanVien
CREATE OR REPLACE TRIGGER TADMIN.TRG_AUDIT_NHANVIEN
AFTER INSERT OR UPDATE OR DELETE ON TADMIN.NhanVien
FOR EACH ROW
DECLARE
    v_action NVARCHAR2(20);
    v_record_id NVARCHAR2(100);
    v_old_values CLOB := '{}';
    v_new_values CLOB := '{}';
    v_user NVARCHAR2(100);
BEGIN
    v_action := CASE WHEN INSERTING THEN 'INSERT' WHEN UPDATING THEN 'UPDATE' WHEN DELETING THEN 'DELETE' END;
    v_user := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));

    IF v_action = 'DELETE' THEN
        v_record_id := :OLD.MaNhanVien;
        v_old_values := JSON_OBJECT('MANHANVIEN' VALUE :OLD.MANHANVIEN, 'HOTEN' VALUE :OLD.HOTEN, 'EMAIL' VALUE :OLD.EMAIL, 'VAITRO' VALUE :OLD.VAITRO, 'TRANGTHAI' VALUE :OLD.TRANGTHAI, 'MACHINHANH' VALUE :OLD.MACHINHANH);
    ELSE
        v_record_id := :NEW.MaNhanVien;
    END IF;

    IF v_action = 'INSERT' THEN
        v_new_values := JSON_OBJECT('MANHANVIEN' VALUE :NEW.MANHANVIEN, 'HOTEN' VALUE :NEW.HOTEN, 'EMAIL' VALUE :NEW.EMAIL, 'VAITRO' VALUE :NEW.VAITRO, 'TRANGTHAI' VALUE :NEW.TRANGTHAI, 'MACHINHANH' VALUE :NEW.MACHINHANH);
    ELSIF v_action = 'UPDATE' THEN
        DECLARE
            json_obj_old JSON_OBJECT_T := JSON_OBJECT_T();
            json_obj_new JSON_OBJECT_T := JSON_OBJECT_T();
        BEGIN
            IF DECODE(:OLD.HOTEN, :NEW.HOTEN, 0, 1) = 1 THEN json_obj_old.put('HOTEN', :OLD.HOTEN); json_obj_new.put('HOTEN', :NEW.HOTEN); END IF;
            IF DECODE(:OLD.EMAIL, :NEW.EMAIL, 0, 1) = 1 THEN json_obj_old.put('EMAIL', :OLD.EMAIL); json_obj_new.put('EMAIL', :NEW.EMAIL); END IF;
            IF DECODE(:OLD.SODIENTHOAI, :NEW.SODIENTHOAI, 0, 1) = 1 THEN json_obj_old.put('SODIENTHOAI', :OLD.SODIENTHOAI); json_obj_new.put('SODIENTHOAI', :NEW.SODIENTHOAI); END IF;
            IF DECODE(:OLD.VAITRO, :NEW.VAITRO, 0, 1) = 1 THEN json_obj_old.put('VAITRO', :OLD.VAITRO); json_obj_new.put('VAITRO', :NEW.VAITRO); END IF;
            IF DECODE(:OLD.TRANGTHAI, :NEW.TRANGTHAI, 0, 1) = 1 THEN json_obj_old.put('TRANGTHAI', :OLD.TRANGTHAI); json_obj_new.put('TRANGTHAI', :NEW.TRANGTHAI); END IF;
            IF DECODE(:OLD.MACHINHANH, :NEW.MACHINHANH, 0, 1) = 1 THEN json_obj_old.put('MACHINHANH', :OLD.MACHINHANH); json_obj_new.put('MACHINHANH', :NEW.MACHINHANH); END IF;
            v_old_values := json_obj_old.to_clob();
            v_new_values := json_obj_new.to_clob();
        END;
    END IF;

    IF v_action IN ('INSERT', 'DELETE') OR (v_action = 'UPDATE' AND v_old_values != '{}') THEN
        INSERT INTO TADMIN.AUDIT_LOG_DETAIL (TableName, Action, ActionBy, RecordId, OldValues, NewValues)
        VALUES ('NhanVien', v_action, v_user, v_record_id, v_old_values, v_new_values);
    END IF;
END;
/

-- Trigger cho bảng Tour
CREATE OR REPLACE TRIGGER TADMIN.TRG_AUDIT_TOUR
AFTER INSERT OR UPDATE OR DELETE ON TADMIN.Tour
FOR EACH ROW
DECLARE
    v_action NVARCHAR2(20);
    v_record_id NVARCHAR2(100);
    v_old_values CLOB := '{}';
    v_new_values CLOB := '{}';
    v_user NVARCHAR2(100);
BEGIN
    v_action := CASE WHEN INSERTING THEN 'INSERT' WHEN UPDATING THEN 'UPDATE' WHEN DELETING THEN 'DELETE' END;
    v_user := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));

    IF v_action = 'DELETE' THEN
        v_record_id := :OLD.MaTour;
        v_old_values := JSON_OBJECT('MATOUR' VALUE :OLD.MATOUR, 'TIEUDE' VALUE :OLD.TIEUDE, 'GIANGUOILON' VALUE :OLD.GIANGUOILON, 'TRANGTHAI' VALUE :OLD.TRANGTHAI, 'SOLUONG' VALUE :OLD.SOLUONG);
    ELSE
        v_record_id := :NEW.MaTour;
    END IF;

    IF v_action = 'INSERT' THEN
        v_new_values := JSON_OBJECT('MATOUR' VALUE :NEW.MATOUR, 'TIEUDE' VALUE :NEW.TIEUDE, 'GIANGUOILON' VALUE :NEW.GIANGUOILON, 'TRANGTHAI' VALUE :NEW.TRANGTHAI, 'SOLUONG' VALUE :NEW.SOLUONG);
    ELSIF v_action = 'UPDATE' THEN
        DECLARE
            json_obj_old JSON_OBJECT_T := JSON_OBJECT_T();
            json_obj_new JSON_OBJECT_T := JSON_OBJECT_T();
        BEGIN
            IF DECODE(:OLD.TIEUDE, :NEW.TIEUDE, 0, 1) = 1 THEN json_obj_old.put('TIEUDE', :OLD.TIEUDE); json_obj_new.put('TIEUDE', :NEW.TIEUDE); END IF;
            IF DECODE(:OLD.NOIKHOIHANH, :NEW.NOIKHOIHANH, 0, 1) = 1 THEN json_obj_old.put('NOIKHOIHANH', :OLD.NOIKHOIHANH); json_obj_new.put('NOIKHOIHANH', :NEW.NOIKHOIHANH); END IF;
            IF DECODE(:OLD.NOIDEN, :NEW.NOIDEN, 0, 1) = 1 THEN json_obj_old.put('NOIDEN', :OLD.NOIDEN); json_obj_new.put('NOIDEN', :NEW.NOIDEN); END IF;
            IF DECODE(:OLD.THOIGIAN, :NEW.THOIGIAN, 0, 1) = 1 THEN json_obj_old.put('THOIGIAN', TO_CHAR(:OLD.THOIGIAN, 'YYYY-MM-DD')); json_obj_new.put('THOIGIAN', TO_CHAR(:NEW.THOIGIAN, 'YYYY-MM-DD')); END IF;
            IF DECODE(:OLD.GIANGUOILON, :NEW.GIANGUOILON, 0, 1) = 1 THEN json_obj_old.put('GIANGUOILON', :OLD.GIANGUOILON); json_obj_new.put('GIANGUOILON', :NEW.GIANGUOILON); END IF;
            IF DECODE(:OLD.GIATREEM, :NEW.GIATREEM, 0, 1) = 1 THEN json_obj_old.put('GIATREEM', :OLD.GIATREEM); json_obj_new.put('GIATREEM', :NEW.GIATREEM); END IF;
            IF DECODE(:OLD.TRANGTHAI, :NEW.TRANGTHAI, 0, 1) = 1 THEN json_obj_old.put('TRANGTHAI', :OLD.TRANGTHAI); json_obj_new.put('TRANGTHAI', :NEW.TRANGTHAI); END IF;
            IF DECODE(:OLD.SOLUONG, :NEW.SOLUONG, 0, 1) = 1 THEN json_obj_old.put('SOLUONG', :OLD.SOLUONG); json_obj_new.put('SOLUONG', :NEW.SOLUONG); END IF;
            v_old_values := json_obj_old.to_clob();
            v_new_values := json_obj_new.to_clob();
        END;
    END IF;

    IF v_action IN ('INSERT', 'DELETE') OR (v_action = 'UPDATE' AND v_old_values != '{}') THEN
        INSERT INTO TADMIN.AUDIT_LOG_DETAIL (TableName, Action, ActionBy, RecordId, OldValues, NewValues)
        VALUES ('Tour', v_action, v_user, v_record_id, v_old_values, v_new_values);
    END IF;
END;
/

-- Trigger cho bảng DatTour
CREATE OR REPLACE TRIGGER TADMIN.TRG_AUDIT_DATTOUR
AFTER INSERT OR UPDATE OR DELETE ON TADMIN.DatTour
FOR EACH ROW
DECLARE
    v_action NVARCHAR2(20);
    v_record_id NVARCHAR2(100);
    v_old_values CLOB := '{}';
    v_new_values CLOB := '{}';
    v_user NVARCHAR2(100);
BEGIN
    v_action := CASE WHEN INSERTING THEN 'INSERT' WHEN UPDATING THEN 'UPDATE' WHEN DELETING THEN 'DELETE' END;
    v_user := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));

    IF v_action = 'DELETE' THEN
        v_record_id := :OLD.MaDatTour;
        v_old_values := JSON_OBJECT('MADATTOUR' VALUE :OLD.MADATTOUR, 'TRANGTHAITHANHTOAN' VALUE :OLD.TRANGTHAITHANHTOAN, 'TRANGTHAIDAT' VALUE :OLD.TRANGTHAIDAT);
    ELSE
        v_record_id := :NEW.MaDatTour;
    END IF;

    IF v_action = 'INSERT' THEN
        v_new_values := JSON_OBJECT('MADATTOUR' VALUE :NEW.MADATTOUR, 'MAKHACHHANG' VALUE :NEW.MAKHACHHANG, 'MATOUR' VALUE :NEW.MATOUR, 'TONGTIEN' VALUE :NEW.TONGTIEN, 'TRANGTHAITHANHTOAN' VALUE :NEW.TRANGTHAITHANHTOAN, 'TRANGTHAIDAT' VALUE :NEW.TRANGTHAIDAT);
    ELSIF v_action = 'UPDATE' THEN
        DECLARE
            json_obj_old JSON_OBJECT_T := JSON_OBJECT_T();
            json_obj_new JSON_OBJECT_T := JSON_OBJECT_T();
        BEGIN
            IF DECODE(:OLD.SONGUOILON, :NEW.SONGUOILON, 0, 1) = 1 THEN json_obj_old.put('SONGUOILON', :OLD.SONGUOILON); json_obj_new.put('SONGUOILON', :NEW.SONGUOILON); END IF;
            IF DECODE(:OLD.SOTREEM, :NEW.SOTREEM, 0, 1) = 1 THEN json_obj_old.put('SOTREEM', :OLD.SOTREEM); json_obj_new.put('SOTREEM', :NEW.SOTREEM); END IF;
            IF DECODE(:OLD.TONGTIEN, :NEW.TONGTIEN, 0, 1) = 1 THEN json_obj_old.put('TONGTIEN', :OLD.TONGTIEN); json_obj_new.put('TONGTIEN', :NEW.TONGTIEN); END IF;
            IF DECODE(:OLD.TRANGTHAITHANHTOAN, :NEW.TRANGTHAITHANHTOAN, 0, 1) = 1 THEN json_obj_old.put('TRANGTHAITHANHTOAN', :OLD.TRANGTHAITHANHTOAN); json_obj_new.put('TRANGTHAITHANHTOAN', :NEW.TRANGTHAITHANHTOAN); END IF;
            IF DECODE(:OLD.TRANGTHAIDAT, :NEW.TRANGTHAIDAT, 0, 1) = 1 THEN json_obj_old.put('TRANGTHAIDAT', :OLD.TRANGTHAIDAT); json_obj_new.put('TRANGTHAIDAT', :NEW.TRANGTHAIDAT); END IF;
            v_old_values := json_obj_old.to_clob();
            v_new_values := json_obj_new.to_clob();
        END;
    END IF;

    IF v_action IN ('INSERT', 'DELETE') OR (v_action = 'UPDATE' AND v_old_values != '{}') THEN
        INSERT INTO TADMIN.AUDIT_LOG_DETAIL (TableName, Action, ActionBy, RecordId, OldValues, NewValues)
        VALUES ('DatTour', v_action, v_user, v_record_id, v_old_values, v_new_values);
    END IF;
END;
/

-- =================================================================================
-- PHẦN 4: HƯỚNG DẪN SỬ DỤNG VÀ LƯU Ý
-- =================================================================================
-- 1. Để xem kết quả audit:
--    - Xem tất cả: SELECT * FROM TADMIN.AUDIT_LOG_DETAIL ORDER BY ActionTimestamp DESC;
--    - Lọc theo bảng (ví dụ 'NhanVien'):
--      Trong C# hoặc SQL Developer, bạn có thể gọi procedure:
--      VAR rc REFCURSOR;
--      EXEC TADMIN.GET_AUDIT_LOGS('NhanVien', :rc);
--      PRINT rc;

-- 2. Về việc ghi nhận "Người thực hiện" (ActionBy):
--    - Cột "ActionBy" sẽ hiển thị giá trị của `SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER')`.
--    - Để giá trị này là tên người dùng (ví dụ: 'NV001', 'KH002'), ứng dụng ASP.NET
--      cần phải thiết lập định danh này ngay sau khi mở kết nối database.
--    - Ví dụ trong C# sử dụng Oracle.ManagedDataAccess.Client:
--      var cmd = connection.CreateCommand();
--      cmd.CommandText = "BEGIN DBMS_SESSION.SET_IDENTIFIER(:id); END;";
--      cmd.Parameters.Add(new OracleParameter("id", "TEN_USER_DANG_NHAP"));
--      cmd.ExecuteNonQuery();
--    - Dựa trên file OracleSessionInterceptor.cs, có vẻ logic này đã tồn tại.
--      Hãy đảm bảo interceptor này được kích hoạt và `User.Identity.Name` có giá trị
--      bạn mong muốn. Nếu ActionBy vẫn là 'TADMIN', vấn đề nằm ở phía ứng dụng.
-- =================================================================================